trustedStreamers:
  - NeunEinser
  - ThomasToSpace
  - slicedlime
  - noleafcloverlp
  - kimandjax
  - CracaCG
  - gothfaerie
  - JamCow
  - LeeP1z
  - mrquisling
  - RofoRex
  - the_guy1604
  - minecraftleanne