# This is your local config.
# You may override anything set in default.yml as well, for example to test on
# your own private testserver and seting the ids accordingly.

# Following are configurations that are not set in default.yml containing
# tokens and secrets.

### NEVER COMMIT ANY TOKEN OR ANY SECRET ###

# This is the token for your Discord bot account
discordToken: <discord bot token>

# This holds information for your Twitch App.
twitch:
  clientId: <twitch client id>
  clientSecret: <twitch client secret>
  # The event sub secret can be anything and should be a random string of characters
  eventSubSecret: <eventsub secret>

# If you want to test locally without a certificate, do not define ssl and setup
# Ngork on your system instead. https://ngrok.com/
#
# To use ngork, simply don't specify the ssl object in your file.
#
# If this is set, the bot will use your domain and certificate.
ssl:
  hostName: <your domain name>
  certificate: <the location of your certificate file including all intermediate certifcates>
  key: <the private key belonging to your certificate>